{{ range $.Values.services }}
{{- if .enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    getambassador.io/config: | 
    {{- range .annotations }}
    {{ . | nindent 6 }}
    {{- end }}
  labels: 
    app.kubernetes.io/name: {{ $.Chart.Name }}
    helm.sh/chart: {{ $.Chart.Name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/part-of:  {{ $.Chart.Name }}
    app.kubernetes.io/version: ${project.version}
spec:
  type: {{ .type }}
  ports:
    - port: {{ .port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ $.Chart.Name }}
    helm.sh/chart: {{ $.Chart.Name }}
{{- end }}
{{ end }}