apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: demo-scs-run-
spec:
  pipelineRef:
    name: maven-build
  resources:
  - name: app-git
    resourceSpec:
      type: git
      params:
        - name: url
          value: https://github.com/marc-heimann/demo-scs
  workspaces:
  - name: local-maven-repo
    persistentVolumeClaim:
      claimName: maven-repo-pvc